import '../../env';
import { SupportedLocales } from '@/dictionaries';
import './../globals.css';
import { Inter } from 'next/font/google';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: { lang: SupportedLocales };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
